# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Install
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
